# Generated by Django 5.0.3 on 2025-11-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidayfree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tollid', models.CharField(max_length=25, verbose_name='收费单元编号')),
                ('stationno', models.SmallIntegerField(verbose_name='收费站编号')),
                ('laneno', models.SmallIntegerField(verbose_name='车道编号')),
                ('lanecomputerip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('lanetype', models.CharField(max_length=16, verbose_name='车道类型')),
                ('verid', models.CharField(blank=True, max_length=16, null=True, verbose_name='版本号')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='免费开始时间')),
                ('overtime', models.DateTimeField(blank=True, null=True, verbose_name='免费结束时间')),
                ('inspector', models.CharField(max_length=32, verbose_name='检查人员')),
                ('inspecttime', models.DateTimeField(blank=True, null=True, verbose_name='检查时间')),
                ('inspectresult', models.CharField(max_length=32, verbose_name='检查结果')),
                ('confirmer', models.CharField(blank=True, max_length=32, null=True, verbose_name='确认人员')),
                ('confirmdatetime', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('isconfirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
        ),
    ]
