# Generated by Django 5.0.3 on 2025-11-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidayfree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayfree',
            options={'ordering': ['stationno', 'laneno']},
        ),
    ]
