from django.db import models
class Vehlossrate(models.Model):
    tolllaneid = models.CharField(verbose_name="国标车道编码", max_length=25)
    stationid = models.CharField(verbose_name="国标站编码", max_length=25)
    stationno = models.SmallIntegerField(verbose_name="收费站编号")
    laneno = models.SmallIntegerField(verbose_name="车道编号")
    lanetypename = models.CharField(verbose_name="车道类型", max_length=16, null=True, blank=True)
    lanecomputerip = models.GenericIPAddressField(verbose_name="设备IP")
    cnt = models.IntegerField(verbose_name="交易数量", null=True, blank=True)
    veh = models.IntegerField(verbose_name="抓拍数量", null=True, blank=True)
    scu = models.IntegerField(verbose_name="识别数量", null=True, blank=True)
    per = models.FloatField(verbose_name="抓拍率", null=True, blank=True)
    per1 = models.FloatField(verbose_name="总识别率", null=True, blank=True)
    per2 = models.FloatField(verbose_name="有牌识别率", null=True, blank=True)
    starttime = models.CharField(verbose_name="开始时间", max_length=32, null=True, blank=True)
    endtime = models.CharField(verbose_name="结束时间", max_length=32, null=True, blank=True)
    inspector = models.CharField(verbose_name="检查人员", max_length=32)
    inspecttime = models.CharField(verbose_name="检查时间", max_length=32, null=True, blank=True)
    isconfirm = models.BooleanField(verbose_name='是否确认', default=False)
