# Generated by Django 5.0.3 on 2025-11-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetypename', models.CharField(max_length=16, verbose_name='设备类型')),
            ],
        ),
        migrations.CreateModel(
            name='SubnetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnettypename', models.CharField(max_length=16, verbose_name='子网名称')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('devicename', models.CharField(max_length=50, verbose_name='设备名称')),
                ('position', models.CharField(max_length=32, verbose_name='安装位置')),
                ('devicemanufacture', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备厂商')),
                ('unittype', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备型号')),
                ('deviceserialnumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备序列号')),
                ('user1', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户1')),
                ('pwd1', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码1')),
                ('user2', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户2')),
                ('pwd2', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码2')),
                ('user3', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户3')),
                ('pwd3', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码3')),
                ('user4', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户4')),
                ('pwd4', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码4')),
                ('mem', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('devicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceinfo', related_query_name='deviceinfo', to='devicemgmt.devicetype', verbose_name='设备类型')),
                ('subnetwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceinfo', related_query_name='deviceinfo', to='devicemgmt.subnettype', verbose_name='子网')),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
