# Generated by Django 5.0.3 on 2025-11-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psamstatus', models.CharField(max_length=16, verbose_name='psam卡状态')),
            ],
        ),
        migrations.CreateModel(
            name='LanePsamInfo',
            fields=[
                ('deviceid', models.CharField(max_length=30, verbose_name='收费单元编号')),
                ('stationno', models.SmallIntegerField(verbose_name='收费站编号')),
                ('laneno', models.SmallIntegerField(verbose_name='车道编号')),
                ('lanecomputerip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('terminano', models.CharField(blank=True, max_length=20, null=True, verbose_name='终端编号')),
                ('psamno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='PSAM卡卡号')),
                ('first_createtime', models.DateTimeField(blank=True, null=True, verbose_name='最初获取时间')),
                ('last_createtime', models.DateTimeField(blank=True, null=True, verbose_name='最后获取时间')),
                ('mem', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('psamstatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lanepsaminfo.psamstatus', verbose_name='PSAM卡状态')),
            ],
        ),
    ]
