# Generated by Django 5.0.3 on 2025-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gantrypsaminfo',
            fields=[
                ('tollid', models.CharField(max_length=30, verbose_name='收费单元编号')),
                ('position', models.CharField(max_length=32, verbose_name='门架区间')),
                ('pilenumber', models.CharField(max_length=16, verbose_name='门架桩号')),
                ('rsuid', models.CharField(max_length=16, verbose_name='RSUID')),
                ('controlid', models.SmallIntegerField(blank=True, null=True, verbose_name='控制器ID')),
                ('channelid', models.SmallIntegerField(blank=True, null=True, verbose_name='通道号')),
                ('psamno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='PSAM卡号')),
                ('statusName', models.CharField(max_length=16, verbose_name='PSAM状态')),
                ('first_createtime', models.DateTimeField(blank=True, null=True, verbose_name='最初获取时间')),
                ('last_createtime', models.DateTimeField(blank=True, null=True, verbose_name='最后获取时间')),
                ('mem', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
    ]
