# Generated by Django 5.0.3 on 2025-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehlossrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolllaneid', models.CharField(max_length=25, verbose_name='国标车道编码')),
                ('stationid', models.CharField(max_length=25, verbose_name='国标站编码')),
                ('stationno', models.SmallIntegerField(verbose_name='收费站编号')),
                ('laneno', models.SmallIntegerField(verbose_name='车道编号')),
                ('lanetypename', models.CharField(blank=True, max_length=16, null=True, verbose_name='车道类型')),
                ('lanecomputerip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('cnt', models.IntegerField(blank=True, null=True, verbose_name='交易数量')),
                ('veh', models.IntegerField(blank=True, null=True, verbose_name='抓拍数量')),
                ('scu', models.IntegerField(blank=True, null=True, verbose_name='识别数量')),
                ('per', models.FloatField(blank=True, null=True, verbose_name='抓拍率')),
                ('per1', models.FloatField(blank=True, null=True, verbose_name='总识别率')),
                ('per2', models.FloatField(blank=True, null=True, verbose_name='有牌识别率')),
                ('starttime', models.CharField(blank=True, max_length=32, null=True, verbose_name='开始时间')),
                ('endtime', models.CharField(blank=True, max_length=32, null=True, verbose_name='结束时间')),
                ('inspector', models.CharField(max_length=32, verbose_name='检查人员')),
                ('inspecttime', models.CharField(blank=True, max_length=32, null=True, verbose_name='检查时间')),
                ('isconfirm', models.BooleanField(default=False, verbose_name='是否确认')),
            ],
        ),
    ]
