# Generated by Django 5.0.3 on 2025-11-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehlossrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehlossrate',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='inspector',
            field=models.CharField(db_index=True, max_length=32, verbose_name='检查人员'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='inspecttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='检查时间'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='isconfirm',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否确认'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='stationid',
            field=models.CharField(db_index=True, max_length=25, verbose_name='国标站编码'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='stationno',
            field=models.SmallIntegerField(db_index=True, verbose_name='收费站编号'),
        ),
        migrations.AlterField(
            model_name='vehlossrate',
            name='tolllaneid',
            field=models.CharField(db_index=True, max_length=25, verbose_name='国标车道编码'),
        ),
        migrations.AlterUniqueTogether(
            name='vehlossrate',
            unique_together={('tolllaneid', 'starttime', 'endtime', 'isconfirm')},
        ),
        migrations.AddIndex(
            model_name='vehlossrate',
            index=models.Index(fields=['tolllaneid', 'starttime', 'endtime'], name='vehlossrate_tolllan_2c1497_idx'),
        ),
        migrations.AddIndex(
            model_name='vehlossrate',
            index=models.Index(fields=['stationno', 'laneno'], name='vehlossrate_station_93976b_idx'),
        ),
    ]
