# Generated by Django 5.0.3 on 2025-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelTable(
            name='opsuser',
            table='sys_user',
        ),
        migrations.AlterModelTable(
            name='requestlog',
            table='sys_requestLog',
        ),
    ]
