# Generated by Django 5.0.3 on 2025-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklanesoft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationno', models.SmallIntegerField(verbose_name='收费站编号')),
                ('tollStationname', models.CharField(max_length=32, verbose_name='收费站')),
                ('laneno', models.SmallIntegerField(verbose_name='车道编号')),
                ('lanetypename', models.CharField(max_length=16, verbose_name='车道类型')),
                ('obublacklistversion', models.CharField(max_length=32, verbose_name='OBU状态名单')),
                ('spcrateversion', models.CharField(max_length=16, verbose_name='最小费率')),
                ('greenreservelistversion', models.CharField(max_length=16, verbose_name='绿通预约')),
                ('bulkvehreserveversion', models.CharField(max_length=16, verbose_name='大件运输车')),
                ('laneservtime', models.CharField(max_length=25, verbose_name='车道时间')),
                ('lanebeidoutime', models.CharField(max_length=30, verbose_name='北斗时间')),
                ('lanerateversion', models.CharField(max_length=30, verbose_name='承载门架费率')),
                ('opsver', models.CharField(max_length=25, verbose_name='车道软件版本')),
                ('inspector', models.CharField(max_length=32, verbose_name='检查人员')),
                ('inspecttime', models.DateTimeField(blank=True, null=True, verbose_name='检查时间')),
                ('inspectresult', models.CharField(blank=True, max_length=32, null=True, verbose_name='检查结果')),
                ('confirmer', models.CharField(blank=True, max_length=32, null=True, verbose_name='确认人员')),
                ('confirmdatetime', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('isconfirm', models.BooleanField(default=False, verbose_name='是否确认')),
                ('error_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='故障描述')),
                ('error_proc', models.CharField(blank=True, max_length=100, null=True, verbose_name='故障处理')),
            ],
        ),
    ]
