# Generated by Django 5.0.3 on 2025-11-28 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devicemgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pingdevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32, verbose_name='桩号')),
                ('devicename', models.CharField(max_length=50, verbose_name='设备名称')),
                ('deviceip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('inspectresult', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '检查失败')], max_length=12, verbose_name='检查结果')),
                ('inspector', models.CharField(max_length=32, verbose_name='检查人员')),
                ('inspecttime', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('confirmer', models.CharField(blank=True, max_length=32, null=True, verbose_name='确认人员')),
                ('confirmdatetime', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('isconfirm', models.BooleanField(default=False, verbose_name='是否确认')),
                ('error_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='故障描述')),
                ('error_proc', models.CharField(blank=True, max_length=100, null=True, verbose_name='故障处理')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='任务ID')),
                ('devicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_devices', to='devicemgmt.devicetype', verbose_name='设备类型')),
            ],
            options={
                'db_table': 'ping_devices',
                'ordering': ['-inspecttime'],
                'indexes': [models.Index(fields=['deviceip', 'inspecttime'], name='ping_device_devicei_6c901f_idx'), models.Index(fields=['task_id'], name='ping_device_task_id_20c80c_idx')],
            },
        ),
    ]
