# Generated by Django 5.0.3 on 2025-11-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0001_initial'),
        ('pingdevices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingdevices',
            name='devicetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ping_devices', to='devicemgmt.devicetype', verbose_name='设备类型'),
        ),
    ]
