# Generated by Django 5.0.3 on 2025-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemgmt', '0001_initial'),
        ('pingdevices', '0002_alter_pingdevices_devicetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pingdevices',
            options={'ordering': ['-deviceip']},
        ),
        migrations.AddConstraint(
            model_name='pingdevices',
            constraint=models.UniqueConstraint(fields=('deviceip',), name='unique_deviceip_per_record'),
        ),
    ]
